site_name: "feedback-spa"
site_description: "this is test"

nav:
  - Introduction: index.md
  - FAQs: faqs.md
  - Contribution: contribution.md
  - Code Of Conduct: coc.md

plugins:
  - techdocs-core
